set CMAKE_OPTIONS=-DNETTY_P2P__ENABLE_QT5=ON ^
    -DNETTY_P2P__ENABLE_NEW_UDT=ON ^
    -DNETTY_P2P__ENABLE_CEREAL=ON

set PROJECT_OPT_PREFIX=NETTY__
set CXX_STANDARD=11
set BUILD_TESTS=ON
set BUILD_DEMO=ON

call build-windows.cmd
