#!/bin/bash

CMAKE_OPTIONS="-DENABLE_QT5=ON \
-DPFS_NET__BUILD_TESTS=ON \
-PFS_NET__BUILD_DEMO=ON \
-DENABLE_NEW_UDT=ON -DENABLE_CEREAL=ON"

PROJECT_OPT_PREFIX=PFS_NET__
CXX_STANDARD=11
BUILD_TESTS=ON
BUILD_DEMO=ON

option(PFS_NET__BUILD_TESTS "Build tests" OFF)
option( "Build examples/demo" OFF)

. ../build.sh
